version: '3'

services:
  web:
    build: .
    command: gunicorn inventory_api.wsgi:application --bind 0.0.0.0:8080 --workers 4
    volumes:
      - .:/code
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
